SRV_APPLET_MGR__BROKER__Keepalive: 3h
SRV_APPLET_MGR__BROKER__QoS: ONCE
SRV_APPLET_MGR__BROKER__RetainPublish: "false"
SRV_APPLET_MGR__BROKER__Retry_Interval: 3s
SRV_APPLET_MGR__BROKER__Retry_Repeats: "3"
SRV_APPLET_MGR__BROKER__Server: mqtt://127.0.0.1:1883
SRV_APPLET_MGR__BROKER__Timeout: 3s

SRV_APPLET_MGR__CONFIG__ResourceRoot: ./asserts
SRV_APPLET_MGR__CONFIG__UploadLimit: "104857600"

SRV_APPLET_MGR__JWT__ExpIn: 1h
SRV_APPLET_MGR__JWT__Issuer: "srv-applet-mgr"
SRV_APPLET_MGR__JWT__SignKey: ""

SRV_APPLET_MGR__LOG__Format: JSON
SRV_APPLET_MGR__LOG__Level: DEBUG
SRV_APPLET_MGR__LOG__Name: "srv-applet-mgr"
SRV_APPLET_MGR__LOG__ReportCaller: "false"
SRV_APPLET_MGR__LOG__Output: ALWAYS

SRV_APPLET_MGR__PGCLI__ConnMaxLifetime: 1h
SRV_APPLET_MGR__PGCLI__Master: postgres://test_user:test_passwd@127.0.0.1:5432/test?sslmode=disable
SRV_APPLET_MGR__PGCLI__PoolSize: "10"
SRV_APPLET_MGR__PGCLI__Retry_Interval: 3s
SRV_APPLET_MGR__PGCLI__Retry_Repeats: "3"
SRV_APPLET_MGR__PGCLI__Slave: ""

SRV_APPLET_MGR__SERVER__Debug: "true"
SRV_APPLET_MGR__SERVER__Port: "8888"
SRV_APPLET_MGR__SERVER__Spec: ./swagger.json
