MOCK_MQTT_CLIENT__BROKER__Keepalive: 3h
MOCK_MQTT_CLIENT__BROKER__QoS: ONCE
MOCK_MQTT_CLIENT__BROKER__RetainPublish: "false"
MOCK_MQTT_CLIENT__BROKER__Retry_Interval: 3s
MOCK_MQTT_CLIENT__BROKER__Retry_Repeats: "3"
MOCK_MQTT_CLIENT__BROKER__Server: mqtt://127.0.0.1:1883
MOCK_MQTT_CLIENT__BROKER__Timeout: 3s
